M48
; DRILL file KiCad 10.0.1 date 2026-05-03T11:00:03
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-03T11:00:03-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X64.855Y-103.11
X64.855Y-108.89
T2
X61.5Y-122.0
X61.5Y-125.0
X106.5Y-93.0
X109.5Y-93.0
T3
X74.5Y-94.5
X74.5Y-140.5
X124.0Y-109.0
X124.0Y-137.0
M30
