M48
; DRILL file KiCad 10.0.0 date 2026-04-30T13:08:55
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-30T13:08:55-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X93.307Y-105.61
X93.307Y-111.39
T2
X53.5Y-100.5
X53.5Y-103.5
X96.575Y-94.25
X96.575Y-97.25
M30
